name: Deply to sea-otter via tailscale

on:
  push:
    branches: [ "main" ]

jobs :
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get lattest code
        uses: actions/checkout@v4

      - name:  go into tailscale VPN
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: latest
      - name: setting for get local repo
        run: |
          echo '{"insecure-registries": ["${{ secrets.SERVER_IP }}:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: build and push to local repo
        run: |
          docker build -t ${{ secrets.SERVER_IP }}:5000/incanedible-be:latest .
          docker push ${{ secrets.SERVER_IP }}:5000/incanedible-be:latest
      - name: ssh to run docker file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/varakorn/incanedible
            docker-compose pull
            docker-compose up -d